.TH MAILNAGGER-CONFIG "1" "Oct 2024" "Mailnag 2.2.1"
.SH NAME
mailnagger-config \- Mailnagger setup utility
.SH SYNOPSIS
\fBmailnagger-config\fP
.SH DESCRIPTION
\fBmailnagger-config\fP is a utility that makes it easy to setup Mailnagger
initially. This only needs to be run once; after running it and closing the
configuration window, Mailnagger will be started automatically.
.SH SEE ALSO
.PP
\fBmailnagger\fP(1)
.SH AUTHOR
\fBmailnagger\fP is forked from Mailnag by Timo Kankare <timo.kankare@iki.fi>.
.PP
\fBmailnag\fP was written by Patrick Ulbrich <zulu99@gmx.net>.
.PP
This manual page was written by Vincent Cheng <Vincentc1208@gmail.com>,
for the Debian project (and may be used by others).
